#!/bin/sh
set -e
PROG=`readlink -m "$0"`
DIR=`dirname "$PROG"`
if [ -r $DIR/.classpath ]; then
    source $DIR/.classpath
fi
java -Dawt.useSystemAAFontSettings=on -cp $CLASSPATH org.nyet.ecuxplot.ECUxPlot "$@"
