#!/bin/sh

cd ..

for source in $*; do
    dest=`basename $source .kp`
    stem=`echo $source | cut -d - -f 1`
    if [ -r data/$source ]; then
	echo "reading data/$source"
	./mapdump -r data/4Z7907551R.kp -r data/8D0907551F.kp -r data/8D0907551G.kp -i data/$stem.bin data/$source > data/$dest.csv
	./mapdump -r data/4Z7907551R.kp -r data/8D0907551F.kp -r data/8D0907551G.kp -i data/$stem.bin -x data/$source > data/$dest.xdf
    else
	echo "can't read data/$source"
    fi
done
