#!/bin/sh
[ -z "$1" ] && exit -1
#url=`svn info | grep -i "^url:" | cut -f 2- -d :`
root=`svn info | grep -i "^repository root:" | cut -f 2- -d :`
echo "removing existing tag $1"
svn delete $root/tags/$1 -m "removing existing tag $1"
echo "tagging $1"
svn cp $root/trunk $root/tags/$1 -m "tagging $1"
