name: Build All Platforms

on:
  workflow_call:
    inputs:
      use-cache:
        required: false
        type: boolean
        default: false
        description: 'Whether to use runtime caching'

jobs:

  build-macos:
    uses: ./.github/workflows/build-common.yml
    with:
      platform: 'macos'
      build-target: 'installers'
      artifact-paths: |
        build/*-MacOS.zip
        build/*.dmg
        ECUxPlot.dmg
      use-cache: ${{ inputs.use-cache }}
    secrets: inherit

  build-linux-windows:
    uses: ./.github/workflows/build-common.yml
    with:
      platform: linux
      build-target: installers
      artifact-paths: |
        build/*.tar.gz
        build/*-setup.exe
        build/ECUxPlot-*.jar
        ECUxPlot.jar
        mapdump.jar
        ECUxPlot-setup.exe
      use-cache: ${{ inputs.use-cache }}
    secrets: inherit
