---
name: Build Platform

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
        description: 'Platform to build for (linux, macos)'
      build-target:
        required: true
        type: string
        description: 'Make target to run (all, exes, dmg, installers)'
      artifact-paths:
        required: false
        type: string
        description: 'Semicolon-separated list of artifact paths to upload'
      use-cache:
        required: false
        type: boolean
        default: false
        description: 'Whether to use runtime caching'
      asset-version:
        required: false
        type: string
        default: ''
        description: 'Asset version suffix (nightly for nightly builds, empty for releases)'

jobs:
  build:
    runs-on: ${{ inputs.platform == 'macos' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up JDK 18
      uses: actions/setup-java@v5
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Cache runtime directories
      if: inputs.use-cache
      uses: actions/cache@v4
      with:
        path: |
          runtime/*
        key: runtime-cache-${{ inputs.platform }}-${{ hashFiles('scripts/java-target.mk', 'scripts/download-jre.sh') }}

    - name: Install build tools
      run: |
        if [ "${{ inputs.platform }}" = "linux" ]; then
          sudo apt-get update
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get install -y --no-install-recommends make ant nsis mingw-w64 binutils-mingw-w64 dos2unix python3-yaml
          make install-launch4j
        elif [ "${{ inputs.platform }}" = "macos" ]; then
          pip3 install --break-system-packages pyyaml
        fi

    - name: Build targets
      run: |
        if [ -n "${{ inputs.asset-version }}" ]; then
          make ${{ inputs.build-target }} ASSET_VER=${{ inputs.asset-version }}
        else
          make ${{ inputs.build-target }}
        fi
      env:
        DISPLAY: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: |
        make test
      env:
        DISPLAY: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create simple installer names
      run: |
        # Create simple names for main installers only
        if [ "${{ inputs.platform }}" = "macos" ]; then
          # macOS DMG
          for dmg in build/ECUxPlot-*.dmg; do
            if [ -f "$dmg" ]; then
              cp "$dmg" ECUxPlot.dmg
              echo "Created ECUxPlot.dmg from $(basename $dmg)"
            fi
          done
        elif [ "${{ inputs.platform }}" = "linux" ]; then
          # Windows setup.exe
          for exe in build/ECUxPlot-*-setup.exe; do
            if [ -f "$exe" ]; then
              cp "$exe" ECUxPlot-setup.exe
              echo "Created ECUxPlot-setup.exe from $(basename $exe)"
            fi
          done
        fi

    - name: Upload artifacts
      if: inputs.artifact-paths != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.platform == 'linux' && 'linux-windows-builds' || 'macos-builds' }}
        path: |
          ${{ inputs.artifact-paths }}
