---
name: Build ECUxPlot Multi-Platform

on:
  push:

jobs:
  build-macos:
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: macos
      build-target: archive

  build-linux:
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: linux
      build-target: exes
      artifact-paths: |
        build/CYGWIN_NT/*.exe
        ECUxPlot-*.jar
        mapdump.jar
